### ISSUE TITLE
how to set TabBarItem title or only use title?

### ISSUE THREAD

**Issue by leiyong316** [Goles/GGTabBar#2]
i have 2 Issuses.

First:  set TabBarItem title invalid.
![image](https://cloud.githubusercontent.com/assets/2143362/5791744/a3508cb0-9f26-11e4-9d83-c866341ee571.png)

second: if i use title only, not need use image. how to set?
![4334dca0-511c-4c88-aff6-20ba4c5986c2](https://cloud.githubusercontent.com/assets/2143362/5791755/d7bfc136-9f27-11e4-9e3d-a42b812130fd.png)

thanks

**Comment by Goles** [comment]
Hey there, 

I'll be working on this ;) 

More like a feature request though :+1:

**Comment by Goles** [comment]
Hey there @leiyong316 , I've been very busy because I'm moving to San Francisco, CA. I'll have more time to look into this in a couple of weeks I guess! (the solution is not totally trivial)

Cheers!

**Comment by Goles** [comment]
Hey @leiyong316 , I haven't had the time to work on this (moving to a new country is a lot of work). Did you happen to implement this functionality? I'll mark this as a feature request, also if you're willing to show me your implementation or send a pull request I could merge stuff in.

**Comment by leiyong316** [comment]
Currently I am engaged in big data hadoop related work,    IOS put aside.

thanks

**Comment by Goles** [comment]
@leiyong316 No prob, I'll try to implement this if I have the time.

Cheers and thanks for closing.
