### ISSUE TITLE
How to hide GGTabBar?

### ISSUE THREAD

**Issue by edison0951** [Goles/GGTabBar#5]
When push to some sub viewcontroller, I need hide the tabbar, so how can I do it?

**Comment by Goles** [comment]
Could you be more specific? 

I might expose a way to hide the TabBar, but don't know what most people would need.

**Comment by edison0951** [comment]
for example, tabbar viewcontroller have 4 sub naviagationController,  the navigationController have a tableView or collectionView, so I selct one cell and it will push to another viewController ,so the new viewController need hide tabbar, when I pop the new viewController, I need show tabbar again. It just like hidesBottomBarWhenPushed.

**Comment by Goles** [comment]
I'll take a look at it this weekend.

Thanks for the feature request :)

On 7/1/15 6:28 PM, riven wrote:
>
> for example, tabbar viewcontroller have 4 sub naviagationController, 
> the navigationController have a tableView or collectionView, so I 
> selct one cell and it will push to another viewController ,so the new 
> viewController need hide tabbar, when I pop the new viewController, I 
> need show tabbar again. It just like hidesBottomBarWhenPushed.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Goles/GGTabBar/issues/5#issuecomment-117869156>.
>

*Nicolas Goles*
Phone # +1 (415) 734-0537
Linkedin <https://www.linkedin.com/in/ngoles> | Twitter 
<http://www.twitter.com/ngoles> | Blog <http://www.nicolasgoles.com/>

**Comment by edison0951** [comment]
My project need it right now.So how can I do if you haven't supply that property

**Comment by Goles** [comment]
For what you want, if I understood correctly you just need to keep a reference to GGTabBar and possible just present it inside another container UIView, then you could basically do whatever you want.

**Comment by edison0951** [comment]
thanks, it works.

**Comment by Goles** [comment]
Cool, will close.
